### ISSUE TITLE
AMD loading seems to have died: 'Bugsense is undefined'.

### ISSUE THREAD

**Issue by samkelleher** [bugsense/bugsense.js#33]
Example:
```
define(['path/to/bugsense'], function(Bugsense) {
// Bugsense is undefined, as is window.Bugsense
// The correct AMD JS file has however been loaded normally.
});
```

Any ideas?

While I'm here I'd like a way to prevent Bugsense adding itself globally and taking control of window.onerror.  In the application I'm working on the application centrally manages the errors since there is more than one subscriber to the event.

Also there is no documentation on how to change the user_identifier once the logger has been initialized.

**Comment by samkelleher** [comment]
I think you must be using a hardcoded export as this works:
```
requirejs.config({
    "paths": {
        "bugsense": "path/to/amd/bugsense"
    }
});
define(['bugsense'], function(Bugsense) {
// Bugsense is now a thing
});
```

This is all case-sensitive by the way.

**Comment by tsironis** [comment]
Hello @samkelleher,

Unfortunately, we just dropped support for these SDKs last week, in favor of the new Splunk MInt SDKs. You can though, by all means, fork this repo make your own fixes and changes.

Sorry for any inconvenience caused. Please make sure that you follow our progress concerning new SDK releases.
